"""
DXCC entity lookup from callsign prefixes.

Maps amateur radio callsign prefixes to their DXCC entity name.
The table covers all current DXCC entities with their primary prefixes.
Lookup tries longest prefix first so sub-entities (EA6 → Balearic Is.)
take priority over their parent (EA → Spain).
"""

import re
from typing import Dict, List, Tuple

# Prefix → DXCC entity.  Longer prefixes MUST appear before shorter ones
# that share the same start (handled by the lookup algorithm, not ordering).
_DXCC_MAP: Dict[str, str] = {
    # 1
    '1A': 'Sov. Mil. Order of Malta',
    # 3
    '3A': 'Monaco',
    '3B8': 'Mauritius',
    '3B9': 'Rodriguez Is.',
    '3C0': 'Annobon Is.',
    '3C': 'Equatorial Guinea',
    '3D2': 'Fiji',
    '3DA': 'Eswatini',
    '3V': 'Tunisia',
    '3W': 'Vietnam',
    '3X': 'Guinea',
    # 4
    '4J': 'Azerbaijan',
    '4K': 'Azerbaijan',
    '4L': 'Georgia',
    '4O': 'Montenegro',
    '4S': 'Sri Lanka',
    '4U1I': 'ITU HQ',
    '4U1U': 'United Nations HQ',
    '4X': 'Israel',
    '4Z': 'Israel',
    # 5
    '5A': 'Libya',
    '5B': 'Cyprus',
    '5H': 'Tanzania',
    '5N': 'Nigeria',
    '5R': 'Madagascar',
    '5T': 'Mauritania',
    '5U': 'Niger',
    '5V': 'Togo',
    '5W': 'Samoa',
    '5X': 'Uganda',
    '5Z': 'Kenya',
    # 6
    '6W': 'Senegal',
    '6Y': 'Jamaica',
    # 7
    '7O': 'Yemen',
    '7P': 'Lesotho',
    '7Q': 'Malawi',
    '7X': 'Algeria',
    # 8
    '8P': 'Barbados',
    '8Q': 'Maldives',
    '8R': 'Guyana',
    # 9
    '9A': 'Croatia',
    '9G': 'Ghana',
    '9H': 'Malta',
    '9J': 'Zambia',
    '9K': 'Kuwait',
    '9L': 'Sierra Leone',
    '9M6': 'East Malaysia',
    '9M8': 'East Malaysia',
    '9M2': 'West Malaysia',
    '9M4': 'West Malaysia',
    '9M': 'West Malaysia',
    '9N': 'Nepal',
    '9Q': 'Dem. Rep. of the Congo',
    '9U': 'Burundi',
    '9V': 'Singapore',
    '9X': 'Rwanda',
    '9Y': 'Trinidad & Tobago',
    # A
    'A2': 'Botswana',
    'A3': 'Tonga',
    'A4': 'Oman',
    'A5': 'Bhutan',
    'A6': 'United Arab Emirates',
    'A7': 'Qatar',
    'A9': 'Bahrain',
    'AP': 'Pakistan',
    # B
    'BV': 'Taiwan',
    'BM': 'Taiwan',
    'BN': 'Taiwan',
    'BO': 'Taiwan',
    'BP': 'Taiwan',
    'BQ': 'Taiwan',
    'BU': 'Taiwan',
    'BW': 'Taiwan',
    'BX': 'Taiwan',
    'BY': 'China',
    'BA': 'China',
    'BD': 'China',
    'BG': 'China',
    'BH': 'China',
    'BI': 'China',
    'BJ': 'China',
    'BL': 'China',
    'BR': 'China',
    'BS': 'China',
    'BT': 'China',
    'BZ': 'China',
    'B': 'China',
    # C
    'C2': 'Nauru',
    'C3': 'Andorra',
    'C5': 'The Gambia',
    'C6': 'Bahamas',
    'C9': 'Mozambique',
    'CE0Y': 'Easter Is.',
    'CE0Z': 'Juan Fernandez Is.',
    'CE0X': 'San Felix & San Ambrosio',
    'CE9': 'Antarctica',
    'CE': 'Chile',
    'CM': 'Cuba',
    'CO': 'Cuba',
    'CN': 'Morocco',
    'CP': 'Bolivia',
    'CT3': 'Madeira Is.',
    'CT': 'Portugal',
    'CQ': 'Portugal',
    'CS': 'Portugal',
    'CU': 'Azores',
    'CX': 'Uruguay',
    'CY0': 'Sable Is.',
    'CY9': 'St. Paul Is.',
    # D
    'D2': 'Angola',
    'D4': 'Cape Verde',
    'D6': 'Comoros',
    'DA': 'Fed. Rep. of Germany',
    'DB': 'Fed. Rep. of Germany',
    'DC': 'Fed. Rep. of Germany',
    'DD': 'Fed. Rep. of Germany',
    'DE': 'Fed. Rep. of Germany',
    'DF': 'Fed. Rep. of Germany',
    'DG': 'Fed. Rep. of Germany',
    'DH': 'Fed. Rep. of Germany',
    'DI': 'Fed. Rep. of Germany',
    'DJ': 'Fed. Rep. of Germany',
    'DK': 'Fed. Rep. of Germany',
    'DL': 'Fed. Rep. of Germany',
    'DM': 'Fed. Rep. of Germany',
    'DN': 'Fed. Rep. of Germany',
    'DO': 'Fed. Rep. of Germany',
    'DP': 'Fed. Rep. of Germany',
    'DQ': 'Fed. Rep. of Germany',
    'DR': 'Fed. Rep. of Germany',
    'DU': 'Philippines',
    'DV': 'Philippines',
    'DW': 'Philippines',
    'DX': 'Philippines',
    'DY': 'Philippines',
    'DZ': 'Philippines',
    # E
    'E4': 'Palestine',
    'E5': 'South Cook Is.',
    'E6': 'Niue',
    'E7': 'Bosnia-Herzegovina',
    'EA6': 'Balearic Is.',
    'EB6': 'Balearic Is.',
    'EC6': 'Balearic Is.',
    'ED6': 'Balearic Is.',
    'EE6': 'Balearic Is.',
    'EF6': 'Balearic Is.',
    'EG6': 'Balearic Is.',
    'EH6': 'Balearic Is.',
    'EA8': 'Canary Is.',
    'EB8': 'Canary Is.',
    'EC8': 'Canary Is.',
    'ED8': 'Canary Is.',
    'EE8': 'Canary Is.',
    'EF8': 'Canary Is.',
    'EG8': 'Canary Is.',
    'EH8': 'Canary Is.',
    'EA9': 'Ceuta & Melilla',
    'EB9': 'Ceuta & Melilla',
    'EC9': 'Ceuta & Melilla',
    'ED9': 'Ceuta & Melilla',
    'EE9': 'Ceuta & Melilla',
    'EF9': 'Ceuta & Melilla',
    'EG9': 'Ceuta & Melilla',
    'EH9': 'Ceuta & Melilla',
    'EA': 'Spain',
    'EB': 'Spain',
    'EC': 'Spain',
    'ED': 'Spain',
    'EE': 'Spain',
    'EF': 'Spain',
    'EG': 'Spain',
    'EH': 'Spain',
    'EI': 'Ireland',
    'EJ': 'Ireland',
    'EK': 'Armenia',
    'EL': 'Liberia',
    'EP': 'Iran',
    'EQ': 'Iran',
    'ER': 'Moldova',
    'ES': 'Estonia',
    'ET': 'Ethiopia',
    'EU': 'Belarus',
    'EV': 'Belarus',
    'EW': 'Belarus',
    'EX': 'Kyrgyzstan',
    'EY': 'Tajikistan',
    'EZ': 'Turkmenistan',
    # F
    'FG': 'Guadeloupe',
    'FH': 'Mayotte',
    'FJ': 'St. Barthelemy',
    'FK': 'New Caledonia',
    'FM': 'Martinique',
    'FO': 'French Polynesia',
    'FP': 'St. Pierre & Miquelon',
    'FR': 'Reunion Is.',
    'FS': 'French St. Martin',
    'FT5W': 'Crozet Is.',
    'FT5X': 'Kerguelen Is.',
    'FT5Z': 'Amsterdam & St. Paul Is.',
    'FW': 'Wallis & Futuna Is.',
    'FY': 'French Guiana',
    'F': 'France',
    # G
    'GD': 'Isle of Man',
    'GI': 'Northern Ireland',
    'GJ': 'Jersey',
    'GM': 'Scotland',
    'GU': 'Guernsey',
    'GW': 'Wales',
    'G': 'England',
    'MD': 'Isle of Man',
    'MI': 'Northern Ireland',
    'MJ': 'Jersey',
    'MM': 'Scotland',
    'MU': 'Guernsey',
    'MW': 'Wales',
    'M': 'England',
    '2D': 'Isle of Man',
    '2I': 'Northern Ireland',
    '2J': 'Jersey',
    '2M': 'Scotland',
    '2U': 'Guernsey',
    '2W': 'Wales',
    '2E': 'England',
    # H
    'H4': 'Solomon Is.',
    'HA': 'Hungary',
    'HG': 'Hungary',
    'HB0': 'Liechtenstein',
    'HB': 'Switzerland',
    'HE': 'Switzerland',
    'HC8': 'Galapagos Is.',
    'HC': 'Ecuador',
    'HD': 'Ecuador',
    'HH': 'Haiti',
    'HI': 'Dominican Republic',
    'HJ': 'Colombia',
    'HK0M': 'Malpelo Is.',
    'HK0S': 'San Andres & Providencia',
    'HK0': 'San Andres & Providencia',
    'HK': 'Colombia',
    'HL': 'Republic of Korea',
    'HP': 'Panama',
    'HR': 'Honduras',
    'HS': 'Thailand',
    'HV': 'Vatican City',
    'HZ': 'Saudi Arabia',
    # I
    'IS': 'Sardinia',
    'IM': 'Sardinia',
    'IT9': 'Sicily',
    'IT': 'Italy',
    'I': 'Italy',
    # J
    'J2': 'Djibouti',
    'J3': 'Grenada',
    'J5': 'Guinea-Bissau',
    'J6': 'St. Lucia',
    'J7': 'Dominica',
    'J8': 'St. Vincent',
    'JA': 'Japan',
    'JB': 'Japan',
    'JC': 'Japan',
    'JD': 'Japan',
    'JE': 'Japan',
    'JF': 'Japan',
    'JG': 'Japan',
    'JH': 'Japan',
    'JI': 'Japan',
    'JJ': 'Japan',
    'JK': 'Japan',
    'JL': 'Japan',
    'JM': 'Japan',
    'JN': 'Japan',
    'JO': 'Japan',
    'JP': 'Japan',
    'JQ': 'Japan',
    'JR': 'Japan',
    'JS': 'Japan',
    '7J': 'Japan',
    '7K': 'Japan',
    '7L': 'Japan',
    '7M': 'Japan',
    '7N': 'Japan',
    'JT': 'Mongolia',
    'JU': 'Mongolia',
    'JV': 'Mongolia',
    'JW': 'Svalbard',
    'JX': 'Jan Mayen',
    'JY': 'Jordan',
    # K / W / N / AA-AK (United States)
    'KG4': 'Guantanamo Bay',
    'KH0': 'Mariana Is.',
    'KH1': 'Baker & Howland Is.',
    'KH2': 'Guam',
    'KH3': 'Johnston Is.',
    'KH4': 'Midway Is.',
    'KH5K': 'Kingman Reef',
    'KH5': 'Palmyra & Jarvis Is.',
    'KH6': 'Hawaii',
    'KH7': 'Hawaii',
    'KH8': 'American Samoa',
    'KH9': 'Wake Is.',
    'KL': 'Alaska',
    'AL': 'Alaska',
    'NL': 'Alaska',
    'WL': 'Alaska',
    'KP1': 'Navassa Is.',
    'KP2': 'US Virgin Is.',
    'KP3': 'Puerto Rico',
    'KP4': 'Puerto Rico',
    'KP5': 'Desecheo Is.',
    'K': 'United States',
    'W': 'United States',
    'N': 'United States',
    'AA': 'United States',
    'AB': 'United States',
    'AC': 'United States',
    'AD': 'United States',
    'AE': 'United States',
    'AF': 'United States',
    'AG': 'United States',
    'AH': 'United States',
    'AI': 'United States',
    'AJ': 'United States',
    'AK': 'United States',
    # L
    'LA': 'Norway',
    'LB': 'Norway',
    'LC': 'Norway',
    'LD': 'Norway',
    'LE': 'Norway',
    'LF': 'Norway',
    'LG': 'Norway',
    'LH': 'Norway',
    'LI': 'Norway',
    'LJ': 'Norway',
    'LK': 'Norway',
    'LL': 'Norway',
    'LM': 'Norway',
    'LN': 'Norway',
    'LU': 'Argentina',
    'LV': 'Argentina',
    'LW': 'Argentina',
    'LO': 'Argentina',
    'LP': 'Argentina',
    'LQ': 'Argentina',
    'LR': 'Argentina',
    'LS': 'Argentina',
    'LT': 'Argentina',
    'LX': 'Luxembourg',
    'LY': 'Lithuania',
    'LZ': 'Bulgaria',
    # O
    'OA': 'Peru',
    'OB': 'Peru',
    'OC': 'Peru',
    'OD': 'Lebanon',
    'OE': 'Austria',
    'OH0': 'Aland Is.',
    'OG0': 'Aland Is.',
    'OF0': 'Aland Is.',
    'OI0': 'Aland Is.',
    'OJ0': 'Market Reef',
    'OH': 'Finland',
    'OF': 'Finland',
    'OG': 'Finland',
    'OI': 'Finland',
    'OK': 'Czech Republic',
    'OL': 'Czech Republic',
    'OM': 'Slovakia',
    'ON': 'Belgium',
    'OO': 'Belgium',
    'OP': 'Belgium',
    'OQ': 'Belgium',
    'OR': 'Belgium',
    'OS': 'Belgium',
    'OT': 'Belgium',
    'OX': 'Greenland',
    'OY': 'Faroe Is.',
    'OZ': 'Denmark',
    # P
    'P2': 'Papua New Guinea',
    'P4': 'Aruba',
    'P5': 'DPR of Korea',
    'PA': 'Netherlands',
    'PB': 'Netherlands',
    'PC': 'Netherlands',
    'PD': 'Netherlands',
    'PE': 'Netherlands',
    'PF': 'Netherlands',
    'PG': 'Netherlands',
    'PH': 'Netherlands',
    'PI': 'Netherlands',
    'PJ2': 'Curacao',
    'PJ4': 'Bonaire',
    'PJ5': 'Saba & St. Eustatius',
    'PJ6': 'Saba & St. Eustatius',
    'PJ7': 'Sint Maarten',
    'PP': 'Brazil',
    'PQ': 'Brazil',
    'PR': 'Brazil',
    'PS': 'Brazil',
    'PT': 'Brazil',
    'PU': 'Brazil',
    'PV': 'Brazil',
    'PW': 'Brazil',
    'PX': 'Brazil',
    'PY': 'Brazil',
    'PZ': 'Suriname',
    # R / U (Russia / former USSR)
    'R': 'European Russia',
    'RA': 'European Russia',
    'RB': 'European Russia',
    'RC': 'European Russia',
    'RD': 'European Russia',
    'RE': 'European Russia',
    'RF': 'European Russia',
    'RG': 'European Russia',
    'RJ': 'European Russia',
    'RK': 'European Russia',
    'RL': 'European Russia',
    'RM': 'European Russia',
    'RN': 'European Russia',
    'RO': 'European Russia',
    'RP': 'European Russia',
    'RQ': 'European Russia',
    'RR': 'European Russia',
    'RS': 'European Russia',
    'RT': 'European Russia',
    'RU': 'European Russia',
    'RV': 'European Russia',
    'RW': 'European Russia',
    'RX': 'European Russia',
    'RY': 'European Russia',
    'RZ': 'European Russia',
    'UA': 'European Russia',
    'UB': 'European Russia',
    'UC': 'European Russia',
    'UD': 'European Russia',
    'UE': 'European Russia',
    'UF': 'European Russia',
    'UG': 'European Russia',
    'UH': 'European Russia',
    'UI': 'European Russia',
    'UK': 'Uzbekistan',
    'UN': 'Kazakhstan',
    'UO': 'Kazakhstan',
    'UP': 'Kazakhstan',
    'UQ': 'Kazakhstan',
    'UR': 'Ukraine',
    'US': 'Ukraine',
    'UT': 'Ukraine',
    'UU': 'Ukraine',
    'UV': 'Ukraine',
    'UW': 'Ukraine',
    'UX': 'Ukraine',
    'UY': 'Ukraine',
    'UZ': 'Ukraine',
    # S
    'S0': 'Western Sahara',
    'S2': 'Bangladesh',
    'S5': 'Slovenia',
    'S7': 'Seychelles',
    'S9': 'Sao Tome & Principe',
    'SA': 'Sweden',
    'SB': 'Sweden',
    'SC': 'Sweden',
    'SD': 'Sweden',
    'SE': 'Sweden',
    'SF': 'Sweden',
    'SG': 'Sweden',
    'SH': 'Sweden',
    'SI': 'Sweden',
    'SJ': 'Sweden',
    'SK': 'Sweden',
    'SL': 'Sweden',
    'SM': 'Sweden',
    'SN': 'Poland',
    'SO': 'Poland',
    'SP': 'Poland',
    'SQ': 'Poland',
    'SR': 'Poland',
    'ST': 'Sudan',
    'SU': 'Egypt',
    'SV5': 'Dodecanese',
    'SV9': 'Crete',
    'SV': 'Greece',
    'SW': 'Greece',
    'SX': 'Greece',
    'SY': 'Greece',
    'SZ': 'Greece',
    # T
    'T2': 'Tuvalu',
    'T30': 'Western Kiribati',
    'T31': 'Central Kiribati',
    'T32': 'Eastern Kiribati',
    'T33': 'Banaba Is.',
    'T5': 'Somalia',
    'T7': 'San Marino',
    'T8': 'Palau',
    'TA': 'Turkey',
    'TB': 'Turkey',
    'TC': 'Turkey',
    'TF': 'Iceland',
    'TG': 'Guatemala',
    'TI9': 'Cocos Is.',
    'TI': 'Costa Rica',
    'TJ': 'Cameroon',
    'TK': 'Corsica',
    'TL': 'Central African Republic',
    'TN': 'Republic of the Congo',
    'TR': 'Gabon',
    'TT': 'Chad',
    'TU': 'Cote d\'Ivoire',
    'TY': 'Benin',
    'TZ': 'Mali',
    # V
    'V2': 'Antigua & Barbuda',
    'V3': 'Belize',
    'V4': 'St. Kitts & Nevis',
    'V5': 'Namibia',
    'V6': 'Micronesia',
    'V7': 'Marshall Is.',
    'V8': 'Brunei',
    'VA': 'Canada',
    'VB': 'Canada',
    'VC': 'Canada',
    'VD': 'Canada',
    'VE': 'Canada',
    'VF': 'Canada',
    'VG': 'Canada',
    'VO': 'Canada',
    'VX': 'Canada',
    'VY': 'Canada',
    'CF': 'Canada',
    'CG': 'Canada',
    'CH': 'Canada',
    'CI': 'Canada',
    'CJ': 'Canada',
    'CK': 'Canada',
    'CZ': 'Canada',
    'VK9C': 'Cocos (Keeling) Is.',
    'VK9L': 'Lord Howe Is.',
    'VK9N': 'Norfolk Is.',
    'VK9W': 'Willis Is.',
    'VK9X': 'Christmas Is.',
    'VK0H': 'Heard Is.',
    'VK0M': 'Macquarie Is.',
    'VK': 'Australia',
    'AX': 'Australia',
    'VP2E': 'Anguilla',
    'VP2M': 'Montserrat',
    'VP2V': 'British Virgin Is.',
    'VP5': 'Turks & Caicos Is.',
    'VP6': 'Pitcairn Is.',
    'VP8': 'Falkland Is.',
    'VP9': 'Bermuda',
    'VQ9': 'Chagos Is.',
    'VR': 'Hong Kong',
    'VU4': 'Andaman & Nicobar Is.',
    'VU7': 'Lakshadweep Is.',
    'VU': 'India',
    # X
    'XE': 'Mexico',
    'XF': 'Mexico',
    'XT': 'Burkina Faso',
    'XU': 'Cambodia',
    'XW': 'Laos',
    'XX9': 'Macao',
    'XY': 'Myanmar',
    'XZ': 'Myanmar',
    # Y
    'YA': 'Afghanistan',
    'YB': 'Indonesia',
    'YC': 'Indonesia',
    'YD': 'Indonesia',
    'YE': 'Indonesia',
    'YF': 'Indonesia',
    'YG': 'Indonesia',
    'YH': 'Indonesia',
    'YI': 'Iraq',
    'YJ': 'Vanuatu',
    'YK': 'Syria',
    'YL': 'Latvia',
    'YN': 'Nicaragua',
    'YO': 'Romania',
    'YP': 'Romania',
    'YQ': 'Romania',
    'YR': 'Romania',
    'YS': 'El Salvador',
    'YT': 'Serbia',
    'YU': 'Serbia',
    'YV': 'Venezuela',
    'YW': 'Venezuela',
    'YX': 'Venezuela',
    'YY': 'Venezuela',
    # Z
    'Z2': 'Zimbabwe',
    'Z3': 'North Macedonia',
    'Z6': 'Republic of Kosovo',
    'Z8': 'Republic of South Sudan',
    'ZA': 'Albania',
    'ZB': 'Gibraltar',
    'ZC4': 'UK Sov. Base Areas on Cyprus',
    'ZD7': 'St. Helena',
    'ZD8': 'Ascension Is.',
    'ZD9': 'Tristan da Cunha & Gough Is.',
    'ZF': 'Cayman Is.',
    'ZK3': 'Tokelau',
    'ZL7': 'Chatham Is.',
    'ZL8': 'Kermadec Is.',
    'ZL9': 'Auckland & Campbell Is.',
    'ZL': 'New Zealand',
    'ZP': 'Paraguay',
    'ZS8': 'Prince Edward & Marion Is.',
    'ZS': 'South Africa',
    'ZR': 'South Africa',
    'ZT': 'South Africa',
    'ZU': 'South Africa',
}

# Build a sorted lookup list: longest prefix first so sub-entities win.
_SORTED_PREFIXES: List[Tuple[str, str]] = sorted(
    _DXCC_MAP.items(),
    key=lambda kv: len(kv[0]),
    reverse=True,
)

_PORTABLE_RE = re.compile(r'^([A-Z\d]+)/([A-Z\d]+)$')
_PREFIX_RE = re.compile(r'^([A-Z\d]*?\d)')


def callsign_to_dxcc(call: str) -> Tuple[str, str]:
    """Return (dxcc_entity, prefix_used) for a callsign.

    Handles portable indicators (F/EA1ABC uses EA, EA1ABC/P uses EA).
    Returns ('Unknown', prefix) for unrecognised prefixes.
    """
    call = call.upper().strip()

    # Handle portable: take the part that looks like a home callsign.
    # EA1ABC/P → EA1ABC, F/EA1ABC → EA1ABC (longer part is the call)
    m = _PORTABLE_RE.match(call)
    if m:
        a, b = m.group(1), m.group(2)
        if len(b) > len(a):
            call = b
        else:
            call = a

    # Strip remaining suffixes like /QRP, /M, /MM, /AM, /P
    if '/' in call:
        call = call.split('/')[0]

    # Try longest prefix match
    for prefix, entity in _SORTED_PREFIXES:
        if call.startswith(prefix):
            # Extract the area-level prefix (prefix + area digit if present)
            area_m = _PREFIX_RE.match(call)
            area_prefix = area_m.group(1) if area_m else prefix
            return entity, area_prefix

    # Fallback
    area_m = _PREFIX_RE.match(call)
    area_prefix = area_m.group(1) if area_m else call[:2]
    return 'Unknown', area_prefix
